name: Build and Test application (Scriptchain)

on:
  push:
    branches:
      - master
  pull_request:
    types: [ closed ]
    branches: [ master ]

jobs:
  # build:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: 16.0.0
      
  #   - name: Go to the frontend directory
  #     run: cd web-application/angular

  #   - name: install all packages
  #     run: npm install

  #   - name: link npm with angular cli
  #     run: npm link @angular/cli

  #   - name: build in production mode
  #     run: ng build --configuration production

  testUI:

    needs: build

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Go to the frontend directory
    - run: cd web-application/angular

    - name: test UI
    - run: npm test

  # testBackend:

  #   needs: build

  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix: [10.x, 12.x, 14.x, 15.x]
    
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: ${{ matrix.node-version }}

  #   - name: Go to the backend directory
  #   - run: cd ../../web-application/node

  #   - name: install all backend packages
  #   - run: npm install

  #   - name: Test backend
  #   - run: npm test
