name: Build and Test application (Scriptchain)

on:
  push:
    branches:
      - master
  pull_request:
    types: [ closed ]
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v16.0.0
      uses: actions/setup-node@v2
      with:
        node-version: 16.0.0

    - name: clear npm cache
      working-directory: ./web-application/angular
      run: npm cache clean -f

    - name: install latest npm version
      working-directory: ./web-application/angular
      run: npm install npm@latest

    - name: install all packages
      working-directory: ./web-application/angular
      run: npm install

    - name: install ansi-colors
      working-directory: ./web-application/angular
      run: npm install -g ansi-colors

    - name: link npm with angular cli
      working-directory: ./web-application/angular
      run: npm link @angular/cli

    - name: build in production mode
      working-directory: ./web-application/angular
      run: npm run build

  testUI:

    # needs: build

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      # with: 
      #   ref: master
      #   path: web-application/angular

    # - name: Go to the frontend directory
    #   run: cd web-application/angular

    # - name: link npm with angular cli
    #   run: npm link @angular/cli

    - name: install latest npm version
      working-directory: ./web-application/angular
      run: npm install npm@latest

    - name: Install packages
      working-directory: ./web-application/angular
      run: npm install

    - name: test UI
      working-directory: ./web-application/angular
      run: npm run test

  testBackend:

    # needs: build

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v16.0.0
      uses: actions/setup-node@v2
      with:
        node-version: 16.0.0

    - name: install latest npm version
      working-directory: ./web-application/node
      run: npm install npm@latest

    - name: install all backend packages
      working-directory: ./web-application/node
      run: npm install

    - name: Test backend
      working-directory: ./web-application/node
      run: npm test
