# Authors and their contributions:
# Vidit: Wrote the whole file.

name: Build and Test DEV application (Scriptchain)

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  ci-cd:
    runs-on: self-hosted

    steps:
      # install all dependencies

      - uses: actions/checkout@v2

      - name: Use Node.js v18.17.1
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.1

      - name: clear npm cache
        working-directory: ./web-application/angular
        run: npm cache clean -f

      - name: install latest npm version
        working-directory: ./web-application/angular
        run: npm install -g npm@9.8.1

      - name: install all packages
        working-directory: ./web-application/angular
        run: npm install -g

      - name: install ansi-colors
        working-directory: ./web-application/angular
        run: npm install -g ansi-colors

      - name: install angular cli
        working-directory: ./web-application/angular
        run: npm install --legacy-peer-deps -g @angular/cli@16.1.4 

      # --------- install all dependencies -----------------

      # configurations

      - name: link npm with angular cli
        working-directory: ./web-application/angular
        run: npm link --legacy-peer-deps @angular/cli

      # build and store output

      - name: build in dev mode
        working-directory: ./web-application/angular
        run: npm run build
